version: "3.9"
services:

  postgres:
    image: postgres:13.5
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "253782511180598qq"
      volumes:
        -./postgresdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  activemq:
    image: rmohr/activemq
    ports:
        - 61616:61616

  planner:
    image: 253782511/planner:latest
    ports:
      - "4567:4567"
    depends_on:
      - postgres
      - activemq
    environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
       SPRING_ACTIVEMQ_BROCKER-URL: tcp://activemq:61616

